# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestExistInTable():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testExistInTable(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1382, 736)
    time.sleep(3)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[@type=\'submit\']")))
    self.driver.find_element(By.XPATH, "//input[@name=\'username\']").send_keys("Admin")
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("admin123")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    time.sleep(3)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//h6[text()=\'Dashboard\']")))
    self.driver.find_element(By.XPATH, "//*[text()=\'Recruitment\']").click()
    time.sleep(3)

# Encuentra la tabla por su xpath
    table = self.driver.find_element(By.XPATH, "//div[@class='oxd-table']")
    # Encuentra todas las filas de la tabla
    rows = table.find_elements(By.XPATH, "//div[@role='row']")
    # Define los valores que quieres validar
    valor1 = "Oscar Julian Duque Ramos"
    valor2 = "Hired"
    # Recorre cada fila y valida si contiene ambos valores
    found = False
    for row in rows:
        # Encuentra todas las celdas (td) en la fila
        cells = row.find_elements(By.XPATH, "//div[@role='cell']")        
        # Extrae el texto de cada celda
        cell_texts = [cell.text for cell in cells]

        # Verifica si ambos valores estan presentes en los textos de las celdas
        if valor1 in cell_texts and valor2 in cell_texts:
            found = True
            print(f"Se encontró la fila con {valor1} y {valor2}.")
            break
    if not found:
        print(f"No se encontró ninguna fila que contenga {valor1} y {valor2}.")

    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//h6[text()=\'Recruitment\']")))
    elements = self.driver.find_elements(By.XPATH, "//div[@role=\'row\']")
    assert len(elements) > 0
    self.vars["nombre"] = self.driver.find_element(By.XPATH, "//*[contains(text(),\'Oscar Julian Duque Ramos\')]").text
    if self.driver.execute_script("return (arguments[0]===\"Oscar Julian Duque Ramos\")", self.vars["nombre"]):
      print("{}".format(self.vars["nombre"]))
      print(f"Encontre el registro")
    else:
      print(f"Sali del if")
  
